name: Node.js Dev CI/CD

on:
  pull_request:      # pull request -> merge ê°€ ë˜ì—ˆì„ ë•Œ Github Action ì‹¤í–‰!
    types: [ closed ]
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ë„ ê°€ëŠ¥í•˜ë„ë¡ í•¨

jobs:
  build:
    # pull ìš”ì²­ì´ devì— merge ë˜ì—ˆì„ ë•Œ ì•„ë˜ stepsë¥¼ ì‹¤í–‰
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'

    runs-on: ubuntu-latest  # ìš°ë¶„íˆ¬ ìµœì‹  ë²„ì „ìœ¼ë¡œ ì‹¤í–‰

    strategy:
      matrix:
        node-version: ['18.x']  # ë…¸ë“œ ë²„ì „ ì§€ì •! ì—¬ëŸ¬ ê°œë„ ê°€ëŠ¥! ['18.x', '14.x'] ìš”ë ‡ê²Œ

    steps:
      # build í•  ì½”ë“œë¥¼ ê°€ì ¸ì˜´ (ì½”ë“œ checkout - githubì—ì„œ ì œê³µí•´ì£¼ëŠ” checkout@v3 ì‚¬ìš©)
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js ì„¸íŒ…
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # dependencies ì„¤ì¹˜, test and build
      - name: Install dependencies
        run: npm ci   # dependencies ì„¤ì¹˜ npm ci, npm install ëª¨ë‘ ë‹¤ ë¨!

      - name: Run Build
        run: npm run build # ë¹Œë“œ

      # ë°°í¬ íŒ¨í‚¤ì§€ ìƒì„±
      - name: Generate deployment package
        run: |
          cp -R .platform dist
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json
          cp Procfile dist/Procfile
          cd dist
          zip -r deploy.zip .

      # ìƒì„±í•œ deploy.zip íŒŒì¼ ë‚´ë¶€ í™•ì¸ìš©!
      - name: Get Zip Inside
        run: zipinfo -1 dist/deploy.zip

      # í˜„ì¬ ì‹œê°„ ì–»ê¸° (Build ì‹œì ì˜ ì‹œê°„ ì–»ê¸°)
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # í•œêµ­ ì‹œê°„ ê³ ë ¤

      # í˜„ì¬ ì‹œê°„ ì¶œë ¥ (ìœ„ì—ì„œ ì–»ì€ build ì‹œì ì˜ ì‹œê°„ ë³´ì—¬ì£¼ê¸°ğŸ¤¯)
      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash

      # Beanstalk ë°°í¬
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACTION_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_ACTION_SECRET_ACCESS_KEY}}
          application_name: test8-dev
          environment_name: Test8-dev-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}  # version_labelì€ ì´ì „ì— ë°°í¬í•œ labelê³¼ ì¤‘ë³µë˜ë©´ ì•ˆë¨!
          use_existing_version_if_available: true
          region: ap-northeast-2
          deployment_package: dist/deploy.zip
          wait_for_deployment: false  # ë°”ë¡œ Beanstalkìœ¼ë¡œ ë„˜ì–´ê°ˆ ìˆ˜ ìˆë„ë¡ í•¨

      # ê·¸ëƒ¥ ë‹¤ í–ˆë‹¤ê³  ì¶œë ¥í•˜ê¸°
      - name: Deployed!
        run: echo App deployed to ELB